accounting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finchart.urls')),
]

finchart/urls.py
from django.urls import path
from . import views

app_name = 'finchart'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('company/<int:pk>', views.CompanyView.as_view(), name='company'),
    path('fstatement_detail/<int:pk>', views.FstatementView.as_view(), name='fstatement'),
]

finchart/models.py
from django.db import models
import numpy

class Company(models.Model):
    name = models.CharField("会社名", max_length=30, blank=False)

    def __str__(self):
        return str(self.name)

class Fstatement(models.Model):
    company = models.ForeignKey(Company, on_delete=models.PROTECT)
    fiscal_year = models.DateField("決算日")
    bs_current_assets = models.IntegerField("流動資産（百万円）", default=0)
    bs_fixed_assets = models.IntegerField("固定資産（百万円）", default=0)
    bs_deferred_assets = models.IntegerField("繰延資産（百万円）", default=0)
    bs_current_liabilities = models.IntegerField("流動負債（百万円）", default=0)
    bs_fixed_liabilities = models.IntegerField("固定負債（百万円）", default=0)
    bs_net_assets = models.IntegerField("純資産（百万円）", default=0)
    pl_gross_sales = models.IntegerField("総売上（百万円）", default=0)
    pl_gross_profit = models.IntegerField("売上総利益（百万円）", default=0)
    pl_operating_profit = models.IntegerField("営業利益（百万円）", default=0)
    pl_ordinary_income = models.IntegerField("経常利益（百万円）", default=0)
    pl_income_before_tax = models.IntegerField("税引前当期純利益（百万円）", default=0)
    pl_net_income = models.IntegerField("当期純利益（百万円）", default=0)
    cf_operating = models.IntegerField("営業ＣＦ（百万円）", default=0)
    cf_investment = models.IntegerField("投資ＣＦ（百万円）", default=0)
    cf_finance = models.IntegerField("財務ＣＦ（百万円）", default=0)

    def __str__(self):
        return str(self.company) + '決算日：【 ' + str(self.fiscal_year) + '】'

    def bs_total_assets(self):
        f = self.bs_current_assets + self.bs_fixed_assets + self.bs_deferred_assets
        return f

    def current_assets_rate(self):
        f = numpy.float64(self.bs_current_assets) / self.bs_total_assets() * 100
        return f

    def fixed_assets_rate(self):
        f = numpy.float64(self.bs_fixed_assets) / self.bs_total_assets() * 100
        return f

    def deferred_assets_rate(self):
        f = numpy.float64(self.bs_deferred_assets) / self.bs_total_assets() * 100
        return f

    def current_liabilities_rate(self):
        f = numpy.float64(self.bs_current_liabilities) / self.bs_total_assets() * 100
        return f

    def fixed_liabilities_rate(self):
        f = numpy.float64(self.bs_fixed_liabilities) / self.bs_total_assets() * 100
        return f

    def net_assets_rate(self):
        f = numpy.float64(self.bs_net_assets) / self.bs_total_assets() * 100
        return f

    def gross_profit_rate(self):
        f = numpy.float64(self.pl_gross_profit) / self.pl_gross_sales * 100
        return f

    def operating_profit_rate(self):
        f = numpy.float64(self.pl_operating_profit) / self.pl_gross_sales * 100
        return f

    def ordinary_income_rate(self):
        f = numpy.float64(self.pl_ordinary_income) / self.pl_gross_sales * 100
        return f
    
    def income_before_tax_rate(self):
        f = numpy.float64(self.pl_income_before_tax) / self.pl_gross_sales * 100
        return f

    def net_income_rate(self):
        f = numpy.float64(self.pl_net_income) / self.pl_gross_sales * 100
        return f

    def cf_total_amount(self):
        f = self.cf_operating + self.cf_investment + self.cf_finance
        return f

    def current_rate(self):
        if self.bs_current_liabilities > 0:
            f = numpy.float64(self.bs_current_assets) / self.bs_current_liabilities * 100
        else:
            f = '-'
        return f

    def roe(self):
        f = numpy.float64(self.pl_operating_profit) / self.bs_net_assets * 100
        return f

    def roa(self):
        f = numpy.float64(self.pl_operating_profit) / self.bs_total_assets() * 100
        return f

finchart/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic import TemplateView, DetailView
from .models import Company, Fstatement
from django.views.generic.list import MultipleObjectMixin

class IndexView(TemplateView):
    template_name = "finchart/index.html"

    def get_context_data(self, **kwargs):
        fstatement_list = Fstatement.objects.all().order_by('company')
        params = {
            'fstatement_list': fstatement_list,
        }
        return params

class CompanyView(DetailView, MultipleObjectMixin):
    model = Company
    paginate_by = 4

    def get_context_data(self, **kwargs):
        object_list = Fstatement.objects.filter(company=kwargs['object']).order_by('-fiscal_year')
        context = super(CompanyView, self).get_context_data(object_list=object_list, **kwargs)
        
        return context

class FstatementView(DetailView):
    model = Fstatement

templates/finchart/base.html
{% load static %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Finchart</title>
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">

        <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/> 
        <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="">FinChart</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'finchart:index' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Company
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {% for item in company_list %}
                            <a class="dropdown-item" href="{% url 'finchart:company' item.id %}">{{ item.name }}</a>
                            {% endfor %}
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <main>
            <div class="container">
            {% block content %}
            {% endblock %}
            </div>
        </main>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
    {% block foot %}
    {% endblock %}
</html>

templates/finchart/index.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Djangoアプリケーション</title>
    </head>
    <body>
        {% extends 'finchart/base.html' %}
        {% block content %}
        <script>
            jQuery(function($){
                $.extend( $.fn.dataTable.defaults, {
                    language: {
                        url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
                    }
                    });
                $("#fstatement_list").DataTable({
                    "searching": true,
                    "paging": true,
                    "ordering": true,
                    "lengthChange": true,
                    }).columns.adjust().draw();
            });
        </script>
        <h1>トップページ</h1>
        <table id="fstatement_list" width="100%" class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th class="text-center" width="40%">会社</th>
                <th class="text-center" width="40%">決算日</th>
                <th class="text-center">LINK</th>
            </tr>
            </thead>
            <tbody>
            {% for item in fstatement_list %}
            <tr class="odd gradeX text-center">
                <td class="text-center">{{ item.company }}</td>
                <td class="text-center">{{ item.fiscal_year }}</td>
                <td><a href="{% url 'finchart:fstatement' item.pk %}">詳細へ</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endblock %}
    </body>
</html>

templates/finchart/pagination.html
{% if is_paginated %}
<div class="pagination-bar">
    <nav aria-label="List pagination" class="mb-4">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">前へ</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">前へ</span>
                </li>
            {% endif %}

            {% for page_num in paginator.page_range %}
                {% if page_obj.number == page_num %}
                    <li class="page-item">
                        <span class="page-link active">
                        {{ page_num }}
                        <span class="sr-only">(current)</span>
                        </span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">次へ</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">次へ</span>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endif %}